### ISSUE TITLE
wrong image - Turn off the I2C interface -4,5

### ISSUE THREAD

**Issue by BrahmaFarmsLLC** [jimbobbennett/AgroHack#8]
https://github.com/jimbobbennett/AgroHack/blob/master/Steps/SetUpTheEnvironmentMonitor.md#turn-on-the-i2c-interface

One of the images is missing; this may confuse the users. Just wanted to let you know. attached image below. I dont have push access to add the images... 

<img width="429" alt="pi_I2C_disable" src="https://user-images.githubusercontent.com/60452808/77834250-bf8c8580-7119-11ea-8be8-dabcc53c5480.png">

**Comment by jimbobbennett** [comment]
Images fixed.

If you want to help fix issues, you can always fork the repo and raise a PR! All contributions gratefully received.

**Comment by BrahmaFarmsLLC** [comment]
Sure, will do that
