### ISSUE TITLE
@reboot: command not found

### ISSUE THREAD

**Issue by BrahmaFarmsLLC** [jimbobbennett/AgroHack#9]
I am having issues when I did the crontab entry 

@reboot /home/pi/EnvironmentMonitor/.venv/bin/python3 /home/pi/EnvironmentMonitor/app.py

**Comment by BrahmaFarmsLLC** [comment]
Sorry for premature description of the issue. The issue is under the  
step#3: Write the code to capture telemetry from the Raspberry Pi
under section '**Run the Python app continuously**'

3. Add the following line to the end of the file:
@reboot /home/pi/EnvironmentMonitor/.venv/bin/python3 /home/pi/EnvironmentMonitor/app.py

**Comment by jimbobbennett** [comment]
You still haven’t said what the issue is.

**Comment by BrahmaFarmsLLC** [comment]
I am not receiving the data on the IoT portal. when I try to run the command manually getting this error 
@reboot: command not found

**Comment by jimbobbennett** [comment]
You can't run that command locally -that is a crontab entry, so is triggered on rebooting the device.

Have you tried running the code directly on the Pi? Connect via VS Code, open the folder, ensure the virtual environment is activated then from the terminal do:

```sh
python app.py
```

Does this sent data to IoT Central?

**Comment by BrahmaFarmsLLC** [comment]
Yes, python app.py is working, and I am seeing the data on the IoT Central.

The crontab entry is not triggering after the pi reboot.

**Comment by jimbobbennett** [comment]
Just to check a few things:

* is your username on the pi the default of `pi`?
* If you run the full command `home/pi/EnvironmentMonitor/.venv/bin/python3 /home/pi/EnvironmentMonitor/app.py` does it work?
* How is your pi connecting to the internet?
* There could be an issue where the app is starting up but the Pi isn't connected to the internet, so can you try setting the crontab entry to:
    ```sh
    @reboot sleep 60 && home/pi/EnvironmentMonitor/.venv/bin/python3 /home/pi/EnvironmentMonitor/app.p
    ```

    This will sleep for 1 minute before launching the app

**Comment by BrahmaFarmsLLC** [comment]
Thank you, I will update the settings and let you know

**Comment by BrahmaFarmsLLC** [comment]
It is working now.
